| TID    | Test Data         | Test Case Description                         | PreCondition            | Test Steps                                | Expected Result                                   | Status        | Priority | Is Automated |
|--------|-------------------|-----------------------------------------------|--------------------------|--------------------------------------------|---------------------------------------------------|----------------|----------|--------------|
| TC001 | 0306406152        | Validate a correct ISBN-10 number             | API is up and running   | Pass 0306406152 in the sISBN field         | <IsValidISBN10Result>true</IsValidISBN10Result>  | Not Executed   | High     | Yes          |
| TC002 | 048665088X        | Validate ISBN-10 with 'X' as checksum         | API is up and running   | Pass 048665088X in the sISBN field         | <IsValidISBN10Result>true</IsValidISBN10Result>  | Not Executed   | High     | Yes          |
| TC003 | 1234567890        | Invalid ISBN-10 number                        | API is up and running   | Pass 1234567890 in the sISBN field         | <IsValidISBN10Result>false</IsValidISBN10Result> | Not Executed   | High     | Yes          |
| TC004 | ABCDEFGHIJ        | Test with alphabetic characters               | API is up and running   | Pass ABCDEFGHIJ as sISBN                   | false or error                                   | Not Executed   | Medium   | Yes          |
| TC005 | 12345678X         | 9-digit ISBN ending in 'X'                    | API is up and running   | Pass 12345678X in sISBN field              | false                                            | Not Executed   | Medium   | Yes          |
| TC006 | ""                | Test with empty string input                  | API is up and running   | Pass empty value for sISBN                 | false or error                                   | Not Executed   | High     | Yes          |
| TC007 | null              | Test with null input                          | API is up and running   | Pass null as sISBN                         | Error                                            | Not Executed   | High     | Yes          |
| TC008 | 12345             | Fewer than 10 digits                          | API is up and running   | Pass 5-digit number                        | false or error                                   | Not Executed   | Medium   | Yes          |
| TC009 | 1234567890123     | More than 10 digits                           | API is up and running   | Pass 13-digit number                       | false                                            | Not Executed   | Medium   | Yes          |
| TC010 | 0000000000        | All zeros                                     | API is up and running   | Pass all zeros                             | false                                            | Not Executed   | Medium   | Yes          |
| TC011 | ١٢٣٤٥٦٧٨٩٠       | Arabic numerals                               | API is up and running   | Pass Arabic characters                     | false or error                                   | Not Executed   | Medium   | Yes          |
| TC012 | 一二三四五六七八九十 | Chinese numerals                              | API is up and running   | Pass Chinese digits                        | false or error                                   | Not Executed   | Medium   | Yes          |
| TC013 | 😊😂🤣🧐😎           | Emoji characters                               | API is up and running   | Pass emojis                                | false or error                                   | Not Executed   | Low      | Yes          |
| TC014 | 12@45#78%90       | Special characters                            | API is up and running   | Pass string with symbols                   | false                                            | Not Executed   | Medium   | Yes          |
| TC015 | abc1234567        | Alphanumeric string                           | API is up and running   | Pass alpha-numeric ISBN                    | false                                            | Not Executed   | Medium   | Yes          |
| TC016 | No sISBN param    | Missing sISBN field                           | API is up and running   | Send request without <sISBN>               | false or error                                   | Not Executed   | High     | Yes          |
| TC017 | Invalid XML       | Malformed XML envelope                        | API is up and running   | Send broken SOAP XML                       | Error                                            | Not Executed   | High     | Yes          |
| TC018 | No Headers        | No Content-Type header                        | API is up and running   | Send request without Content-Type          | Error or HTTP 415                                | Not Executed   | High     | Yes          |
| TC019 | Incorrect Content-Type | Wrong header                          | API is up and running   | Use text/plain instead of text/xml         | Error or HTTP 415                                | Not Executed   | High     | Yes          |
| TC020 | Missing SOAP envelope | Missing envelope                         | API is up and running   | Send payload without <Envelope> tag        | Invalid SOAP structure                           | Not Executed   | High     | Yes          |
| TC021 | Cookie not set    | No session/cookie                             | API is up and running   | Send request without cookie                | Should still work                                | Not Executed   | Low      | Yes          |
| TC022 | Extra fields      | Add unrelated XML fields                      | API is up and running   | Add <ExtraTag>Hello</ExtraTag>             | Still returns correct result                     | Not Executed   | Low      | Yes          |
| TC023 | Concurrent Requests | Load test with valid requests              | API is up and running   | Send 50 parallel requests                  | All pass consistently                            | Not Executed   | Medium   | Yes          |
| TC024 | Repeated Request  | Repeat same ISBN multiple times               | API is up and running   | Call same ISBN 5 times                     | All return same result                           | Not Executed   | Medium   | Yes          |
